# Generated by Django 4.1.6 on 2023-02-04 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lvl1Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_name",
                    models.CharField(max_length=100, verbose_name="카테고리 국문 명칭"),
                ),
                (
                    "english_name",
                    models.CharField(max_length=100, verbose_name="카테고리 영문 명칭"),
                ),
                (
                    "is_esri",
                    models.BooleanField(
                        default=True,
                        help_text="본사 카테고리에 포함이 되어있으면 체크표시",
                        verbose_name="본사 카테고리 여부",
                    ),
                ),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Lvl2Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_name",
                    models.CharField(max_length=100, verbose_name="카테고리 국문 명칭"),
                ),
                (
                    "english_name",
                    models.CharField(max_length=100, verbose_name="카테고리 영문 명칭"),
                ),
                (
                    "is_esri",
                    models.BooleanField(
                        default=True,
                        help_text="본사 카테고리에 포함이 되어있으면 체크표시",
                        verbose_name="본사 카테고리 여부",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                (
                    "lvl1_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lvl2_categories",
                        to="category.lvl1category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lvl3Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_name",
                    models.CharField(max_length=100, verbose_name="카테고리 국문 명칭"),
                ),
                (
                    "english_name",
                    models.CharField(max_length=100, verbose_name="카테고리 영문 명칭"),
                ),
                ("code", models.CharField(max_length=8)),
                (
                    "lvl2_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lvl3_categories",
                        to="category.lvl2category",
                    ),
                ),
            ],
        ),
    ]
