# Generated by Django 4.1.6 on 2023-02-04 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lvl1category",
            options={
                "ordering": ["code"],
                "verbose_name": "Category (Lvl 1)",
                "verbose_name_plural": "Categories (Lvl 1)",
            },
        ),
        migrations.AlterModelOptions(
            name="lvl2category",
            options={"ordering": ["code"], "verbose_name": "Categories (Lvl 2)"},
        ),
        migrations.AlterModelOptions(
            name="lvl3category",
            options={
                "ordering": ["code"],
                "verbose_name": "Category (Lvl 3)",
                "verbose_name_plural": "Categories (Lvl 3)",
            },
        ),
    ]
