# Generated by Django 4.1.6 on 2023-02-04 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_lvl1category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lvl2category",
            options={
                "ordering": ["code"],
                "verbose_name": "Category (Lvl 2)",
                "verbose_name_plural": "Categories (Lvl 2)",
            },
        ),
    ]
