# Generated by Django 4.1.6 on 2023-02-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_alter_lvl2category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lvl1category",
            name="full_code",
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name="lvl2category",
            name="full_code",
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AddField(
            model_name="lvl3category",
            name="full_code",
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name="lvl1category",
            name="code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lvl2category",
            name="code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lvl3category",
            name="code",
            field=models.IntegerField(),
        ),
    ]
