# Generated by Django 4.1.6 on 2023-02-08 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0005_remove_lvl1category_full_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryDepth1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_name",
                    models.CharField(
                        help_text="카테고리 국문 명칭",
                        max_length=100,
                        verbose_name="카테고리 국문 명칭",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        help_text="카테고리 영문 명칭",
                        max_length=100,
                        verbose_name="카테고리 영문 명칭",
                    ),
                ),
                ("is_esri", models.BooleanField(default=True)),
                ("code", models.CharField(editable=False, max_length=2, unique=True)),
                ("note", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CategoryDepth2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_name",
                    models.CharField(
                        help_text="카테고리 국문 명칭",
                        max_length=100,
                        verbose_name="카테고리 국문 명칭",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        help_text="카테고리 영문 명칭",
                        max_length=100,
                        verbose_name="카테고리 영문 명칭",
                    ),
                ),
                ("is_esri", models.BooleanField(default=True)),
                ("code", models.CharField(editable=False, max_length=5, unique=True)),
                ("note", models.TextField()),
                (
                    "depth1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories_depth2",
                        to="category.categorydepth1",
                        verbose_name="상위 카테고리",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryDepth3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "korean_name",
                    models.CharField(
                        help_text="카테고리 국문 명칭",
                        max_length=100,
                        verbose_name="카테고리 국문 명칭",
                    ),
                ),
                (
                    "english_name",
                    models.CharField(
                        help_text="카테고리 영문 명칭",
                        max_length=100,
                        verbose_name="카테고리 영문 명칭",
                    ),
                ),
                ("is_esri", models.BooleanField(default=True)),
                ("code", models.CharField(editable=False, max_length=10, unique=True)),
                ("note", models.TextField()),
                (
                    "depth2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories_depth3",
                        to="category.categorydepth2",
                        verbose_name="상위 카테고리",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="lvl2category",
            name="lvl1_category",
        ),
        migrations.RemoveField(
            model_name="lvl3category",
            name="lvl2_category",
        ),
        migrations.DeleteModel(
            name="Lvl1Category",
        ),
        migrations.DeleteModel(
            name="Lvl2Category",
        ),
        migrations.DeleteModel(
            name="Lvl3Category",
        ),
    ]
