# Generated by Django 4.1.6 on 2023-02-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0007_alter_categorydepth1_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorydepth1",
            name="needs_review",
            field=models.BooleanField(
                default=False, help_text="체크하면 회의에서 검토", verbose_name="검토필요"
            ),
        ),
        migrations.AddField(
            model_name="categorydepth2",
            name="needs_review",
            field=models.BooleanField(
                default=False, help_text="체크하면 회의에서 검토", verbose_name="검토필요"
            ),
        ),
        migrations.AddField(
            model_name="categorydepth3",
            name="needs_review",
            field=models.BooleanField(
                default=False, help_text="체크하면 회의에서 검토", verbose_name="검토필요"
            ),
        ),
    ]
