# Generated by Django 4.1.6 on 2023-02-15 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0008_categorydepth1_needs_review_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorydepth3",
            name="is_esri",
        ),
    ]
